services:
  server:
    build:
      context: ./server
      dockerfile: .dockerfile
    container_name: tanksai-server-${NUM}
    networks:
      - public_network
    volumes:
      - sqlite_data:/app/data
    ports:
      - "${PORT}:${PORT}"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  game:
    build:
      context: ./game
      dockerfile: .dockerfile
    container_name: tanksai-game-${NUM}

    cap_add:
      - SYS_ADMIN        # required for nsjail mounts
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined

    networks:
      - private_network   # no internet

    volumes:
      - sqlite_data:/app/data
      - ./bots:/bots:ro   # bot source code (read-only)

    tmpfs:
      - /tmp              # per-bot tmpfs workspace

    restart: "no"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  sqlite_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data

networks:
  private_network:
    driver: bridge
    internal: true
  public_network:
    driver: bridge
